config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "articles#index"     #the root route is also mapped to the index action of ArticlesController.
  resources :articles do
    resources :comments
  end

  namespace :api, defaults: { format: 'json' } do
    resources :articles do
      resources :comments, except: [:new, :edit]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  has_many :comments, dependent: :destroy
  has_one :picture, as: :image
  accepts_nested_attributes_for :picture

  
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

  def have_picture?
    return self.picture && self.picture.image.attached?
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article

  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern
  
    VALID_STATUSES = ['public', 'private', 'archived']
  
    included do
      validates :status, inclusion: { in: VALID_STATUSES }
    end
  
    class_methods do
      def public_count
        where(status: 'public').count
      end
    end
  
    def archived?
      status == 'archived'
    end
  end

app/models/picture.rb
class Picture < ApplicationRecord
    belongs_to :image, polymorphic: true
    has_one_attached :image 
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/articles_controller.rb
class Api::ArticlesController < ApiController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    articles = Article.all
    render json: articles
  end

  def show
    article = Article.find(params[:id])
    render json: article
  end

  def new
    article = Article.new
    article.picture = Picture.new
  end

  def create
    article = Article.new(article_params)
    if article.save
      render json: article, status: :created, location: article
    else
      render json: article.errors, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    article = Article.find(params[:id])

    if article.update(article_params)
      render json: article, status: :created, location: article
    else
      render json: article.errors, status: :unprocessable_entity
    end
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy

    redirect_to root_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status, picture_attributes: [ :id, :name, :image ])
    end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApiController
  before_action :authenticate_user!, only: :destroy

    def index
      article = Article.find(params[:article_id])
      comments = article.comments.all
      render json: comments, status: :created
    end

    def show
      article = Article.find(params[:article_id])
      comments = article.comments.find(params[:id])
      render json: comments, status: :created
    end
  
    def create
        article = Article.find(params[:article_id])
        comment = article.comments.create(comment_params)
        if comment.save
          render json: comment, status: :created
        else
          render json: comment.errors, status: :unprocessable_entity
        end
      end

      def destroy
        article = Article.find(params[:article_id])
        comment = article.comments.find(params[:id])      
        comment.destroy
        if comment.destroy
          render json: comment, status: :created
        else
          render json: comment.errors, status: :unprocessable_entity
        end
      end
    
      private
        def comment_params
          params.require(:comment).permit(:commenter, :body, :status)
        end
end

app/controllers/api_controller.rb
class ApiController < ActionController::API

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
    @article.picture = Picture.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status, picture_attributes: [ :id, :name, :image ])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: :destroy
  
    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
      end

      def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
      end
    
      private
        def comment_params
          params.require(:comment).permit(:commenter, :body, :status)
        end
end

app/helpers/api/api_helper.rb
module Api::ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% @article.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <%= form.fields_for :picture do |p| %>
      Name  : <%= p.text_field :name %><br>
      Ficher: <%= p.file_field :image %>
    <% end %>
<br><br>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
      <% @article.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :status %><br>
      <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </div>
    
    <div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<% if user_signed_in? %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete %><br/>
<% end %>
Our blog has <%= Article.public_count %> articles and counting!

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
    </li>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<%= @article.have_picture? ? image_tag(@article.picture.image, class: "image") : "no pictures" %>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %></li>
  <li><%= link_to "Back", "/" %></li>
</ul>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.label :status %><br>
      <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>